FROM ubuntu:latest
ENTRYPOINT []

RUN sed -i s@/archive.ubuntu.com/@/mirrors.aliyun.com/@g /etc/apt/sources.list
RUN apt clean && apt update && apt install git python3 python3-pip wget systemctl -y

COPY phddns-5.0.0-amd64.deb phddns-5.0.0-amd64.deb
RUN dpkg -i phddns-5.0.0-amd64.deb

COPY docker_cmd_phddns.sh docker_cmd_phddns.sh

CMD ["/bin/bash", "docker_cmd_phddns.sh"]
