FROM ubuntu:latest
ENTRYPOINT []

# RUN sed -i s@/archive.ubuntu.com/@/mirrors.aliyun.com/@g /etc/apt/sources.list
RUN apt clean && apt update && apt install git python3 python3-pip -y

COPY ta-lib-0.4.0-src.tar.gz ta-lib-0.4.0-src.tar.gz
RUN tar -zxvf ta-lib-0.4.0-src.tar.gz && cd /ta-lib && ./configure --prefix=/usr && make && make install

# RUN pip3 config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip3 install numpy pandas TA-Lib pymongo redis pika

RUN git clone https://github.com/zhangsheng377/stock.git --depth=1
ARG RABBITMQ_USER
ARG RABBITMQ_PASSWORD
RUN echo "rabbitmq_user = \"$RABBITMQ_USER\" \n\
rabbitmq_password = \"$RABBITMQ_PASSWORD\" "\
> /stock/UTILS/config_rabbitmq.py

WORKDIR /stock

# ENTRYPOINT ["/stock/docker_cmd_save_policies.sh"]
CMD ["/bin/bash", "docker_cmd_save_policies.sh"]
