FROM ubuntu:latest
ENTRYPOINT []

# RUN sed -i s@/archive.ubuntu.com/@/mirrors.aliyun.com/@g /etc/apt/sources.list
RUN apt clean && apt update && apt install git python3 python3-pip -y

# RUN pip3 config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip3 install Flask gunicorn xmltodict pandas tabulate pymongo matplotlib qiniu redis tushare aria2p pika

RUN git clone https://github.com/zhangsheng377/stock.git --depth=1
ARG QINIU_ACCESS_KEY
ARG QINIU_SECRET_KEY
RUN echo "from db_sheets import db_redis\n\
access_key = \"$QINIU_ACCESS_KEY\" \n\
secret_key = \"$QINIU_SECRET_KEY\" \n\
db_redis.set(\"qiniu_access_key\", access_key)\n\
db_redis.set(\"qiniu_secret_key\", secret_key)"\
> /stock/UTILS/config_qiniu.py

ARG RABBITMQ_USER
ARG RABBITMQ_PASSWORD
RUN echo "rabbitmq_user = \"$RABBITMQ_USER\" \n\
rabbitmq_password = \"$RABBITMQ_PASSWORD\" "\
> /stock/UTILS/config_rabbitmq.py

# COPY config_aria2.py /stock/config_aria2.py

WORKDIR /stock

# ENTRYPOINT ["/stock/docker_cmd.sh"]
CMD ["/bin/bash", "docker_cmd_server.sh"]
