version: "2.4"
services:
  save_tushare:
    image: zhangsheng377/stock_image:latest
    container_name: stock_save_tushare
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    logging:
      options:
        max-size: "10m"
    entrypoint:
      - /bin/bash
      - docker_cmd_save_tushare.sh

  stock:
    image: zhangsheng377/stock_image:latest
    container_name: stock_stock
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "22222:22222"
    logging:
      options:
        max-size: "10m"
    entrypoint:
      - /bin/bash
      - docker_cmd.sh

  save_policies:
    image: zhangsheng377/stock_image:latest
    container_name: stock_save_policies
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    logging:
      options:
        max-size: "10m"
    entrypoint:
      - /bin/bash
      - docker_cmd_save_policies.sh

  server:
    image: zhangsheng377/stock_image:latest
    container_name: stock_server
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "5000:5000"
    logging:
      options:
        max-size: "10m"
    entrypoint:
      - /bin/bash
      - docker_cmd_server.sh

  user_send:
    image: zhangsheng377/stock_image:latest
    container_name: stock_user_send
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    logging:
      options:
        max-size: "10m"
    entrypoint:
      - /bin/bash
      - docker_cmd_user_send.sh
