FROM ubuntu:latest
ENTRYPOINT []

RUN sed -i s@/archive.ubuntu.com/@/mirrors.aliyun.com/@g /etc/apt/sources.list
RUN apt clean && apt update && apt install git python3 python3-pip -y

RUN pip3 config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip3 install Flask gunicorn xmltodict pandas tabulate pymongo matplotlib qiniu redis tushare aria2p

RUN git clone https://github.com/zhangsheng377/stock.git --depth=1

COPY config_aria2.py /stock/config_aria2.py

WORKDIR /stock

# ENTRYPOINT ["/stock/docker_cmd.sh"]
CMD ["/bin/bash", "docker_cmd_server.sh"]
