version: "2.4"
services:
  redis:
    image: redis:latest
    container_name: sys_redis
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /mnt/nfs/zsd_server/docker/data/redis:/data
    ports:
      - "6379:6379"
    logging:
      options:
        max-size: "10m"

  mongo:
    image: mongo:latest
    container_name: sys_mongo
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /mnt/nfs/zsd_server/docker/data/mongo:/data
    ports:
      - "27017:27017"
    logging:
      options:
        max-size: "10m"
  
  rabbit:
    image: rabbitmq:3.9-management
    container_name: sys_rabbitmq
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "5672:5672"
      - "15672:15672"
    logging:
      options:
        max-size: "10m"
