FROM zhangsheng377/stock_base:latest
# ENTRYPOINT []

RUN git clone https://github.com/zhangsheng377/stock.git --depth=1
ARG QINIU_ACCESS_KEY
ARG QINIU_SECRET_KEY
RUN echo "access_key = \"$QINIU_ACCESS_KEY\" \n\
secret_key = \"$QINIU_SECRET_KEY\" "\
> /stock/UTILS/config_qiniu.py

ARG RABBITMQ_USER
ARG RABBITMQ_PASSWORD
RUN echo "rabbitmq_user = \"$RABBITMQ_USER\" \n\
rabbitmq_password = \"$RABBITMQ_PASSWORD\" "\
> /stock/UTILS/config_rabbitmq.py

WORKDIR /stock

# CMD ["/bin/bash"]
